### ISSUE TITLE
Convert java code to javascript

### ISSUE THREAD

**Issue by c0pperdragon** [c0pperdragon/sapphireyours#13]
Make some (any is good enough) runnable version for the browser.

**Comment by c0pperdragon** [comment]
Work on this boring and at the same time difficult task was really slow in the last few months (manually converting code to plain javascript is sooo error-prone due to the lack of static syntax checking).
Not because I would not have the time (only working 30 hours a week), but because I mainly spent my free fridays just slacking.
Go get me in better working discipline, I arranged with my boss that I can come in at my free day and use my office desk for private projects.  This I did today for the first time, and it works perfectly. The current work on Sapphire Yours really feels exactly like my usual job. So my concentration is good and work progresses slowly but steadily.

**Comment by Charilaos** [comment]
That is good to hear. It should feel more rewarding every time you use that day to come one step closer. 

I’ve had a very similar experience recently. I work 40 hours a week I and was spending most evenings actively on friends, family and sports. Something was missing: it felt like I should produce and ship things close to my heart to do something that feels rewarding in the long run. Forced myself into 3 hobby projects - one of which is SY - and my spare time feels way more gratifying now.

Keep it up! I got some people excited by letting them play the unfinished version from 3 years ago. It seems like the (virtually unchanged) concept is still perceived as fresh and fun so many years after the original.

**Comment by c0pperdragon** [comment]
Actually I got a very hacked-together version of the core code running. Most animations and all sounds are missing and the program UI is pretty broken, but it shows that it will eventually get to run in the browser.
If you want to have a peek, just clone the repository to your computer and start the "game/launch.html" file in the Firefox browser. Unfortunately Chrome and Opera will prevent execution from local file system, and I have not set up a test webpage for this.  IE 11 would nominally allow me the execution, but starting openGL fails for some other reasons. Don't know for Safari. If it works already, please let me know.

**Comment by Charilaos** [comment]
I was just testing it out before you fixed the movement issue. Works neatly now! And indeed, Firefox only, Safari won't launch it either. This is also the first time I played on macOS. It needs a little adjustment in the controls: grabbing needs to work with the command key instead of control (ctrl+arrows makes you switch desktop spaces and triggers mission control - too much of a challenge).

![in game tutorial command](https://user-images.githubusercontent.com/3001173/36353304-1431dc88-14c5-11e8-9363-3f906efbe236.png)

**Comment by c0pperdragon** [comment]
The main conversion work is now done. Rest of development continues directly on the new code base in javascript.

**Comment by Charilaos** [comment]
I think the issue deserves some applause even if it's closed already! 👏👏
